function [prmQPSKTransmitter,prmQPSKReceiver,qpskRx,hTx,radio_Tx,radio_Rx] = Tx_Rx_init(rolloff,md_order)
    %TX_RX_INIT Summary of this function goes here
    %   Detailed explanation goes here
    
    platform = "N200/N210/USRP2";
    address  = '192.168.10.2'; 
    USRPGain            = 2;  % Set USRP radio gain
    USRPCenterFrequency = 892*1e6;  % Set USRP radio center frequency
    stopTime            = 2;  % USRP radio transmit time in seconds
    sampleRate          = 10*1e6;
    isHDLCompatible     = false;  % disable to run 'FFT-Based' coarse frequency compensation instead of 'Correlation-Based' for improved performance in MATLAB version.
    printReceivedData   = false;
    captureTime         = 1; % Set radio capture time
    prmQPSKTransmitter = Tx_init(platform, address, sampleRate, USRPCenterFrequency, ...
        USRPGain, stopTime,md_order,rolloff);
    prmQPSKReceiver = Rx_init(platform, address, sampleRate, USRPCenterFrequency, ...
        USRPGain, captureTime, isHDLCompatible,md_order,rolloff);
    
    qpskRx = QPSKReceiver(...
            'ModulationOrder',                      prmQPSKReceiver.ModulationOrder, ...
            'SampleRate',                           prmQPSKReceiver.Fs, ...
            'DecimationFactor',                     prmQPSKReceiver.Decimation, ...
            'FrameSize',                            prmQPSKReceiver.FrameSize, ...
            'HeaderLength',                         prmQPSKReceiver.HeaderLength, ...
            'NumberOfMessage',                      prmQPSKReceiver.NumberOfMessage, ...
            'PayloadLength',                        prmQPSKReceiver.PayloadLength, ...
            'DesiredPower',                         prmQPSKReceiver.DesiredPower, ...
            'AveragingLength',                      prmQPSKReceiver.AveragingLength, ...
            'MaxPowerGain',                         prmQPSKReceiver.MaxPowerGain, ...
            'RolloffFactor',                        prmQPSKReceiver.RolloffFactor, ...
            'RaisedCosineFilterSpan',               prmQPSKReceiver.RaisedCosineFilterSpan, ...
            'InputSamplesPerSymbol',                prmQPSKReceiver.Interpolation, ...
            'MaximumFrequencyOffset',               prmQPSKReceiver.MaximumFrequencyOffset, ...
            'PostFilterOversampling',               prmQPSKReceiver.Interpolation/prmQPSKReceiver.Decimation, ...
            'PhaseRecoveryLoopBandwidth',           prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
            'PhaseRecoveryDampingFactor',           prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
            'TimingRecoveryDampingFactor',          prmQPSKReceiver.TimingRecoveryDampingFactor, ...
            'TimingRecoveryLoopBandwidth',          prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
            'TimingErrorDetectorGain',              prmQPSKReceiver.TimingErrorDetectorGain, ...
            'PreambleDetectorThreshold',            prmQPSKReceiver.PreambleDetectorThreshold, ...    
            'DescramblerBase',                      prmQPSKReceiver.ScramblerBase, ...
            'DescramblerPolynomial',                prmQPSKReceiver.ScramblerPolynomial, ...
            'DescramblerInitialConditions',         prmQPSKReceiver.ScramblerInitialConditions,...
            'BerMask',                              prmQPSKReceiver.BerMask, ...
            'CFCAlgorithm',                         prmQPSKReceiver.CFCAlgorithm, ...
            'PrintOption',                          printReceivedData);
    hTx = QPSKTransmitter(...
                'UpsamplingFactor',             prmQPSKTransmitter.Interpolation, ...
                'RolloffFactor',                prmQPSKTransmitter.RolloffFactor, ...
                'RaisedCosineFilterSpan',       prmQPSKTransmitter.RaisedCosineFilterSpan, ...
                'MessageBits',                  prmQPSKTransmitter.MessageBits, ...
                'MessageLength',                prmQPSKTransmitter.MessageLength, ...
                'NumberOfMessage',              prmQPSKTransmitter.NumberOfMessage, ...
                'ScramblerBase',                prmQPSKTransmitter.ScramblerBase, ...
                'ScramblerPolynomial',          prmQPSKTransmitter.ScramblerPolynomial, ...
                'ScramblerInitialConditions',   prmQPSKTransmitter.ScramblerInitialConditions);
    
    radio_Tx = comm.SDRuTransmitter(...
                        'Platform',             prmQPSKTransmitter.Platform, ...
                        'IPAddress',            prmQPSKTransmitter.Address, ...
                        'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                        'Gain',                 prmQPSKTransmitter.USRPGain, ...
                        'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
    
    
    
    radio_Rx = comm.SDRuReceiver(...
                    'Platform',             prmQPSKReceiver.Platform, ...
                    'IPAddress',            prmQPSKReceiver.Address, ...
                    'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain',                 prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType',       'double');
end

